# Generated by Django 3.0.5 on 2020-04-07 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fotos', '0002_auto_20200407_1921'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='pie',
            field=models.CharField(max_length=500),
        ),
    ]
