# Generated by Django 3.0.5 on 2020-04-30 16:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fotos', '0005_auto_20200430_1650'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificaciones',
            name='f_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='current_user', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fotos.Post'),
        ),
        migrations.AlterField(
            model_name='notificaciones',
            name='s_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
