# Generated by Django 3.0.5 on 2020-04-20 19:39

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_usuario_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='follow',
        ),
        migrations.AddField(
            model_name='usuario',
            name='followers',
            field=models.ManyToManyField(blank=True, related_name='userfollowers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='usuario',
            name='following',
            field=models.ManyToManyField(blank=True, related_name='userfollowing', to=settings.AUTH_USER_MODEL),
        ),
    ]
